### PR TITLE
Simplify Rio client and allow HTTPClient to be passed in

### PR DESCRIPTION
**Pull request by scribe**
* Move creation of the HTTP client into object so two http clients can share an expensive CIO client
* Replace inner client with new syntax to avoid constructing a second client
* Remove now un-needed TokenClient

This effectively halves the number of coroutines we need to support a RioClient.

### CODE REVIEW

**Comment by scribe** [comment]
@david-limbach I have a merge error in the save code. I'm fixing.

**Review by david-limbach — APPROVED** [review]
Do we need to be concerned with 2 or more RioClient instances being created using the same HttpClient when the first one is closed the remaining are hosed?

You'll have to explain to me the need for this.

**Comment by scribe** [comment]
> Do we need to be concerned with 2 or more RioClient instances being created using the same HttpClient when the first one is closed the remaining are hosed?
> 
> You'll have to explain to me the need for this.

If you use the .close() method you will close the HttpClient, but it is also the only expensive part of the whole RioClient and it is credential dependent but not URL dependent while the RioClient is still URL dependent.

**Comment by david-limbach** [comment]
> > Do we need to be concerned with 2 or more RioClient instances being created using the same HttpClient when the first one is closed the remaining are hosed?
> > You'll have to explain to me the need for this.
> 
> If you use the .close() method you will close the HttpClient, but it is also the only expensive part of the whole RioClient and it is credential dependent but not URL dependent while the RioClient is still URL dependent.

I understand, but aren't we going to end up shooting ourselves in the foot by closing 1 RioClient and hosing all the others?
Perhaps a better approach would be for WF to maintain a single RioClient for each RioBroker and then sharing them across the application.

**Review by david-limbach — APPROVED** [review]

**Pull request merged**
